### ISSUE TITLE
Not seeing tenable information represented in ASC

### ISSUE THREAD

**Issue by yerodin** [tenable/integration-asc#2]
I'm seeing where it raises the potential score increase and unhealthy resources value numbers in the recommendations panel, but I'm not seeing any evidence of the information imported from tenable anywhere. Where can I confirm that the information from tenable was actually imported?

**Comment by SteveMcGrath** [comment]
Due to restrictions in the Azure Security Center API, we can only push the summarized information.

**Comment by yerodin** [comment]
thank you Steve. It's weird that the guys at tenable say they have support for azure and recommended this script to us, and yet they have such huge limitations.

**Comment by yerodin** [comment]
Hey @SteveMcGrath , could you provide more details on what the script does? Specifically how this "summarized information" is represented in ASC? I ask this because we see that the Tenable API is sending over the vulnerability data for the Azure IPs, however when we check in ASC after successfully running the script the only change we see is "potential score increase" and "unhealthy resources" values are adjusted, but we see no vulnerability data. Where should we go in ASC to see the vulnerability data?

**Comment by SteveMcGrath** [comment]
You'll only see the severity summaries for a given host under a custom finding.  If you would like to see more detail (such as individual vulns) may I suggest you talk to your Azure rep and let them know you would like this API expanded to support this use case.
